"""Added service table

Revision ID: 107d9a8cb98a
Revises: 18e27ee28e0f
Create Date: 2013-09-25 16:09:33.693041

"""

# revision identifiers, used by Alembic.
revision = '107d9a8cb98a'
down_revision = '18e27ee28e0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('icon', sa.Unicode(), nullable=True),
    sa.Column('short_description', sa.Unicode(), nullable=True),
    sa.Column('long_description', sa.Unicode(), nullable=True),
    sa.Column('additional_resources', sa.Unicode(), nullable=True),
    sa.Column('tips', sa.Unicode(), nullable=True),
    sa.Column('media', sa.Unicode(), nullable=True),
    sa.Column('state', sa.Unicode(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['bf_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'category', sa.Column('state', sa.Unicode(), nullable=True))
    op.add_column(u'category', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column(u'lesson', sa.Column('service_id', sa.Integer(), nullable=True))
    op.add_column(u'lesson', sa.Column('ease', sa.Unicode(), nullable=True))
    op.add_column(u'lesson', sa.Column('description', sa.Unicode(), nullable=True))
    op.drop_column(u'lesson', u'difficulty')
    op.drop_column(u'lesson', u'third_party_service')
    op.drop_column(u'lesson', u'state')
    op.drop_column(u'lesson', u'time_estimate')
    op.drop_column(u'lesson', u'short_description')
    op.drop_column(u'lesson', u'additional_resources')
    op.drop_column(u'lesson', u'tips')
    op.drop_column(u'lesson', u'category_id')
    op.drop_column(u'lesson', u'long_description')
    op.add_column(u'step', sa.Column('creator_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'step', 'creator_id')
    op.add_column(u'lesson', sa.Column(u'long_description', sa.VARCHAR(), nullable=True))
    op.add_column(u'lesson', sa.Column(u'category_id', sa.INTEGER(), nullable=True))
    op.add_column(u'lesson', sa.Column(u'tips', sa.VARCHAR(), nullable=True))
    op.add_column(u'lesson', sa.Column(u'additional_resources', sa.VARCHAR(), nullable=True))
    op.add_column(u'lesson', sa.Column(u'short_description', sa.VARCHAR(), nullable=True))
    op.add_column(u'lesson', sa.Column(u'time_estimate', sa.VARCHAR(), nullable=True))
    op.add_column(u'lesson', sa.Column(u'state', sa.VARCHAR(), nullable=True))
    op.add_column(u'lesson', sa.Column(u'third_party_service', sa.VARCHAR(), nullable=True))
    op.add_column(u'lesson', sa.Column(u'difficulty', sa.VARCHAR(), nullable=True))
    op.drop_column(u'lesson', 'description')
    op.drop_column(u'lesson', 'ease')
    op.drop_column(u'lesson', 'service_id')
    op.drop_column(u'category', 'creator_id')
    op.drop_column(u'category', 'state')
    op.drop_table('service')
    ### end Alembic commands ###
