"""Taking name out of step.

Revision ID: 146486df0f6d
Revises: 45bb159f8773
Create Date: 2013-10-04 14:22:07.060175

"""

# revision identifiers, used by Alembic.
revision = '146486df0f6d'
down_revision = '45bb159f8773'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', u'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column(u'name', sa.VARCHAR(), nullable=True))
    ### end Alembic commands ###
