"""Added new fields.

Revision ID: 173700ac4f26
Revises: None
Create Date: 2013-07-18 12:06:35.102454

"""

# revision identifiers, used by Alembic.
revision = '173700ac4f26'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
