"""Created a rating table.

Revision ID: 18e27ee28e0f
Revises: 59d92e59df91
Create Date: 2013-09-20 11:51:13.610590

"""

# revision identifiers, used by Alembic.
revision = '18e27ee28e0f'
down_revision = '59d92e59df91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_or_step', sa.Unicode(), nullable=True),
    sa.Column('lesson_or_step_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bf_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    ### end Alembic commands ###
