"""Added thing_to_remember class

Revision ID: 1a27a3453938
Revises: 24ee2e7188b
Create Date: 2013-07-20 18:12:01.563187

"""

# revision identifiers, used by Alembic.
revision = '1a27a3453938'
down_revision = '24ee2e7188b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thing_to_remember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Unicode(), nullable=True),
    sa.Column('thing_to_remember', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thing_to_remember')
    ### end Alembic commands ###
