"""Add state to lessons

Revision ID: 1acac3085b66
Revises: 430f2963adb9
Create Date: 2013-09-27 15:56:46.801429

"""

# revision identifiers, used by Alembic.
revision = '1acac3085b66'
down_revision = '430f2963adb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('state', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'state')
    ### end Alembic commands ###
