"""Adding created_dt columns

Revision ID: 1c7d0970bb93
Revises: 23aebf11a764
Create Date: 2013-12-17 16:31:44.040090

"""

# revision identifiers, used by Alembic.
revision = '1c7d0970bb93'
down_revision = '23aebf11a764'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bf_user', sa.Column('created_dt', sa.DateTime(), nullable=True))
    op.add_column('connection', sa.Column('created_dt', sa.DateTime(), nullable=True))
    op.add_column('lesson', sa.Column('created_dt', sa.DateTime(), nullable=True))
    op.add_column('service', sa.Column('created_dt', sa.DateTime(), nullable=True))
    op.add_column('step', sa.Column('created_dt', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'created_dt')
    op.drop_column('service', 'created_dt')
    op.drop_column('lesson', 'created_dt')
    op.drop_column('connection', 'created_dt')
    op.drop_column('bf_user', 'created_dt')
    ### end Alembic commands ###
