"""Changed step description to step_type

Revision ID: 201640d09f8b
Revises: None
Create Date: 2013-07-18 12:17:41.369179

"""

# revision identifiers, used by Alembic.
revision = '201640d09f8b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('step_type', sa.Unicode(), nullable=True))
    op.drop_column('step', u'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column(u'description', sa.VARCHAR(), nullable=True))
    op.drop_column('step', 'step_type')
    ### end Alembic commands ###
