"""Testing created_dt column

Revision ID: 23aebf11a764
Revises: 3d541fc7d342
Create Date: 2013-12-17 16:27:59.031614

"""

# revision identifiers, used by Alembic.
revision = '23aebf11a764'
down_revision = '3d541fc7d342'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_dt', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'created_dt')
    ### end Alembic commands ###
