"""Added thing_to_remember

Revision ID: 24ee2e7188b
Revises: 201640d09f8b
Create Date: 2013-07-20 18:03:09.602245

"""

# revision identifiers, used by Alembic.
revision = '24ee2e7188b'
down_revision = '201640d09f8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('thing_to_remember', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'thing_to_remember')
    ### end Alembic commands ###
