"""Added ordering column

Revision ID: 2f8ea3b8e809
Revises: 4a9ac12ea6bd
Create Date: 2013-10-27 17:59:33.531467

"""

# revision identifiers, used by Alembic.
revision = '2f8ea3b8e809'
down_revision = '4a9ac12ea6bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request', u'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('step', sa.Column('place_in_collection', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'place_in_collection')
    op.alter_column('request', u'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
