"""Took away timezone from userLessons

Revision ID: 3d541fc7d342
Revises: 316d9ed47db1
Create Date: 2013-12-17 16:13:20.988411

"""

# revision identifiers, used by Alembic.
revision = '3d541fc7d342'
down_revision = '316d9ed47db1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_to_lesson', u'start_dt',
               existing_type=sa.types.DateTime(timezone=True),
               type_=sa.types.DateTime(timezone=False)
               )
    op.alter_column('user_to_lesson', u'end_dt',
               existing_type=sa.types.DateTime(timezone=True),
               type_=sa.types.DateTime(timezone=False)
               )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_to_lesson', u'start_dt',
               existing_type=sa.types.DateTime(timezone=False),
               type_=sa.types.DateTime(timezone=True)
               )
    op.alter_column('user_to_lesson', u'end_dt',
               existing_type=sa.DateTime(timezone=False),
               type_=sa.types.DateTime(timezone=True)
               )
    ### end Alembic commands ###
