"""Change step_number to int.

Revision ID: 430f2963adb9
Revises: 107d9a8cb98a
Create Date: 2013-09-25 18:02:23.582384

"""

# revision identifiers, used by Alembic.
revision = '430f2963adb9'
down_revision = '107d9a8cb98a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('step', u'step_number',
               existing_type=sa.INT(),
               nullable=False)
    op.alter_column('step', u'next_step_number',
               existing_type=sa.INT(),
               nullable=True)
    
    ### end Alembic commands ###


def downgrade():
    op.alter_column('step', u'step_number',
               existing_type=sa.UNICODE(),
               nullable=True)
    op.alter_column('step', u'next_step_number',
               existing_type=sa.Unicode(),
               nullable=True)
    ### end Alembic commands ###
