"""Adding requests table.'


Revision ID: 4a9ac12ea6bd
Revises: 146486df0f6d
Create Date: 2013-10-04 18:28:36.242027

"""

# revision identifiers, used by Alembic.
revision = '4a9ac12ea6bd'
down_revision = '146486df0f6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('why', sa.Unicode(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    ### end Alembic commands ###
