"""Adding columns to lessons.

Revision ID: 4ae74c4b3ca0
Revises: 52b9c8f82d15
Create Date: 2013-08-05 15:56:31.222181

"""

# revision identifiers, used by Alembic.
revision = '4ae74c4b3ca0'
down_revision = '52b9c8f82d15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('third_party_service', sa.Unicode(), nullable=True))
    op.add_column('lesson', sa.Column('difficulty', sa.Unicode(), nullable=True))
    op.add_column('lesson', sa.Column('short_description', sa.Unicode(), nullable=True))
    op.add_column('lesson', sa.Column('time_estimate', sa.Unicode(), nullable=True))
    op.add_column('lesson', sa.Column('tips', sa.Unicode(), nullable=True))
    op.add_column('lesson', sa.Column('additional_resources', sa.Unicode(), nullable=True))
    op.add_column('lesson', sa.Column('long_description', sa.Unicode(), nullable=True))
    op.drop_column('lesson', u'url')
    op.drop_column('lesson', u'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column(u'description', sa.VARCHAR(), nullable=True))
    op.add_column('lesson', sa.Column(u'url', sa.VARCHAR(), nullable=True))
    op.drop_column('lesson', 'long_description')
    op.drop_column('lesson', 'additional_resources')
    op.drop_column('lesson', 'tips')
    op.drop_column('lesson', 'time_estimate')
    op.drop_column('lesson', 'short_description')
    op.drop_column('lesson', 'difficulty')
    op.drop_column('lesson', 'third_party_service')
    ### end Alembic commands ###
