"""Change step fields.

Revision ID: 52b9c8f82d15
Revises: 1a27a3453938
Create Date: 2013-07-26 16:28:08.535654

"""

# revision identifiers, used by Alembic.
revision = '52b9c8f82d15'
down_revision = '1a27a3453938'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('step', column_name='url', new_column_name='step_number')
    op.alter_column('step', column_name='next_step', new_column_name='next_step_number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('step', column_name='step_number', new_column_name='url')
    op.alter_column('step', column_name='next_step_number', new_column_name='next_step')
    ### end Alembic commands ###
