"""Added columns to user_to_lesson

Revision ID: 530c0d70d57d
Revises: 2f8ea3b8e809
Create Date: 2013-11-01 14:15:16.414902

"""

# revision identifiers, used by Alembic.
revision = '530c0d70d57d'
down_revision = '2f8ea3b8e809'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_to_lesson', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('user_to_lesson', sa.Column('recent_step_number', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_to_lesson', 'recent_step_number')
    op.drop_column('user_to_lesson', 'completed')
    ### end Alembic commands ###
