"""Adding and removing a few columns.'


Revision ID: 558fcfd1fb
Revises: 4d94c06d5342
Create Date: 2013-10-03 18:17:23.927904

"""

# revision identifiers, used by Alembic.
revision = '558fcfd1fb'
down_revision = '4d94c06d5342'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', u'url')
    op.add_column('service', sa.Column('url', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'url')
    op.add_column('category', sa.Column(u'url', sa.VARCHAR(), nullable=True))
    ### end Alembic commands ###
