"""Added more columns to user

Revision ID: d2074297718
Revises: 541f61ab86ca
Create Date: 2014-02-02 15:09:54.336386

"""

# revision identifiers, used by Alembic.
revision = 'd2074297718'
down_revision = '541f61ab86ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bf_user', sa.Column('twitter', sa.Unicode(), nullable=True))
    op.add_column('bf_user', sa.Column('facebook', sa.Unicode(), nullable=True))
    op.add_column('bf_user', sa.Column('gplus', sa.Unicode(), nullable=True))
    op.add_column('bf_user', sa.Column('linkedin', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bf_user', 'linkedin')
    op.drop_column('bf_user', 'gplus')
    op.drop_column('bf_user', 'facebook')
    op.drop_column('bf_user', 'twitter')
    ### end Alembic commands ###
