"""Adding passowrd reset token to user.

Revision ID: e8bc7cfa219
Revises: 58e4f42fba0c
Create Date: 2013-09-17 00:11:27.137318

"""

# revision identifiers, used by Alembic.
revision = 'e8bc7cfa219'
down_revision = '58e4f42fba0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bf_user', sa.Column('reset_token', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bf_user', 'reset_token')
    ### end Alembic commands ###
